version = 0.1
[default]

[default.global.parameters]
stack_name = "andreadiotallevi"
region = "eu-west-2"

[default.sync.parameters]
profile = "default"

[default.logs.parameters]
profile = "default"
